#!/bin/sh 
#
#  Install
###########################################################################
#
#  Purpose:
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`

if [ ! -r Configuration ]
then
    if [ ! -r Configuration.default ]
    then
	echo "Cannot read Configuration file." | tee -a ${LOG}
	exit 1
    fi
    cp Configuration.default Configuration
fi

. Configuration

# ---------------------
${MKDIR} -p ${DATADIR}
${MKDIR} -p ${WORKINGDIR}
${MKDIR} -p ${DISTRIBDIR}
${MKDIR} -p ${ARCHIVEDIR}
${MKDIR} -p ${MONTHLYDIR}
${MKDIR} -p ${ANNUALDIR}

chmod 755 ./bin/refresh

echo "Installation successful."
exit 0
